name: Versionsapi cli

on:
  workflow_dispatch:

jobs:
  versionsapi:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      repository-projects: write
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: ${{ !github.event.pull_request.head.repo.fork && github.head_ref || '' }}
      - uses: ./.github/actions/gh_create_issue
        id: gh_create_issue
        with:
          title: test
          body: test
          repo: issues
          labels: test
          assignee: katexochen
          project: Constellation bugs
          fields: |
            kubernetesVersion: v1.18.0
            cloudProvider: azure
            test: e2e
            workflow: wf
            refStream: main
          token: ${{ secrets.PROJECT_WRITE_TOKEN }}
      - run: echo ${{ steps.gh_create_issue.outputs.issue-url }}
